### ISSUE TITLE
Skipped tasks are shown as pending

### ISSUE THREAD

**Issue by keskad** [kube-cicd/pipelines-feedback-tekton#29]
Skipped tasks are having their own section in the PipelineRun status, it could be supported in order to correctly show status:

```
skippedTasks:
    - name: lint
      reason: PipelineRun was stopping
      whenExpressions:
        - input: 'true'
          operator: in
          values:
            - 'true'
        - input: springbootJava17
          operator: in
          values:
            - springboot
            - springbootJava11
            - springbootJava17
```
